parser: 'babel-eslint'
plugins:
  - prettier
extends:
  - prettier
rules:
  prettier/prettier:
    - 2
    -
      trailingComma: none
      semi: false
  no-empty-pattern: 0
  prefer-const: 2
  prefer-arrow-callback: 2
  no-unused-vars:
    - 2
    -
      argsIgnorePattern: ^_
      varsIgnorePattern: ^_
